name: Run Test

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: |
        xcodebuild clean test -project AppStoreClone.xcodeproj \
        -scheme AppStoreClone \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
